version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres14_2
    ports:
      - 54322:5432
    volumes:
      - ./db_store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db_store: